spring:
  application:
    name: loom-webflux
  main:
    banner-mode: off
    lazy-initialization: true
  threads:
    virtual:
      enabled: true
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/loom-webflux
    username: postgres
    password: password

server:
  http2:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health, shutdown"
  endpoint:
    shutdown:
      enabled: true

loom-webflux:
  repo-read-only: true
  jvm-metrics-csv-path: bin/jvm.csv
  web-client:
    max-connections: 65000
    connect-timeout: 20s
    pending-acquire-timeout: 60s
    pending-acquire-max-count: ${loom-webflux.web-client.max-connections}
    response-timeout: ${loom-webflux.web-client.pending-acquire-timeout}


