spring:
  application:
    name: loom-webflux
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true

server:
  http2:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health, heapdump, shutdown, threaddump"
  endpoint:
    shutdown:
      enabled: true

loom-webflux:
  default-delay: 100ms
  repo-read-only: true
  jvm-metrics-csv-path: bin/jvm.csv


