spring:
  application:
    name: loom-webflux
  threads:
    virtual:
      enabled: true

server:
  http2:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
