name: infra

services:
  postgres:
    container_name: postgres
    image: postgres:16
    command: -c 'max_connections=500'
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432/tcp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    stdin_open: true
    tty: true

volumes:
  postgres-data:
