name: benchmark
on:
  schedule:
    - cron: '0 2 2 * *' # 2nd of each month at 2am
  workflow_dispatch:
jobs:
  call-reusable-build:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      scenarios-path: config/scenarios.csv
