name: build
on: [ push ]

jobs:
  call-reusable-build:
    uses: ./.github/workflows/reusable-build.yaml
    permissions:
      contents: write
    secrets: inherit
    with:
      scenarios-path: scenarios-smoketest.csv
