name: high-load
on:
  schedule:
    - cron: '0 13 2 * *' # 2nd of each month at 1pm
  workflow_dispatch:
jobs:
  call-reusable-build:
    permissions:
      contents: write  
    uses: ./.github/workflows/reusable-build.yaml
    secrets: inherit
    with:
      scenarios-path: scenarios-high-load.csv
      approaches: loom-netty,webflux-netty
