name: high-load
on:
  schedule:
    - cron: '0 11 2 * *' # 2nd of each month at 11am
  workflow_dispatch:
jobs:
  call-reusable-build:
    uses: ./.github/workflows/reusable-build.yaml
    secrets: inherit
    with:
      scenarios-path: config/scenarios-high-load.csv
      approaches: loom-netty,webflux-netty
