name: soaktest
on:
  schedule:
    - cron: '0 5 * * 0'
  workflow_dispatch:
jobs:
  call-reusable-build:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      scenarios-path: config/scenarios-soaktest.csv
      approaches: loom-netty,webflux-netty
