name: soaktest
on:
  schedule:
    - cron: '0 5 2 * *' # 2nd of each month at 6am
  workflow_dispatch:
jobs:
  call-reusable-build:
    uses: ./.github/workflows/reusable-build.yaml
    secrets: inherit
    with:
      scenarios-path: scenarios-soaktest.csv
      approaches: loom-netty,webflux-netty
