name: soaktest
on:
  schedule:
    - cron: '0 5 2 * *' # 2nd of each month at 5am
  workflow_dispatch:
jobs:
  call-reusable-build:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      scenarios-path: config/scenarios-soaktest.csv
      approaches: loom-netty,webflux-netty
